spring:
  application:
    name: fintech
  datasource:
    url: jdbc:mysql://localhost:3306/fintech
    username: devuser
    password: devpass
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml