spring:
  application:
    name: fintech

  datasource:
    url: ${MYSQL_DB_URL:jdbc:mysql://localhost:3306/fintech}
    username: ${MYSQL_DB_USER:devuser}
    password: ${MYSQL_DB_PASS:devpass}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml